name: QA 앱 빌드
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      bucket_name:
        required: true
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
      KEY_STORE_FILE:
        required: true
      SIGNING_NAME:
        required: true
      SIGNING_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  create-check-run:
    runs-on: ubuntu-latest
    outputs:
      check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
      branch_name: ${{ steps.get_branch_name.outputs.branch_name }}
    steps:
      - name: PR 가져오기
        id: get_pr
        uses: octokit/request-action@v2.1.9
        with:
          route: GET /repos/{repository}/pulls/{pr_number}
          repository: ${{ github.repository }}
          pr_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: PR의 head_sha 가져오기
        id: get_head_sha
        run: echo "head_sha=$(echo ${{ fromJson(steps.get_pr.outputs.data).head.sha }})" >> $GITHUB_OUTPUT
      - name: PR의 branch_name 가져오기
        id: get_branch_name
        run: echo "branch_name=$(echo ${{ fromJson(steps.get_pr.outputs.data).head.ref }})" >> $GITHUB_OUTPUT
      - name: Check Run 생성
        uses: octokit/request-action@v2.1.9
        id: create_check_run
        with:
          route: POST /repos/{repository}/check-runs
          repository: ${{ github.repository }}
          name: "build-app-by-comment"
          head_sha: ${{ steps.get_head_sha.outputs.head_sha }}
          status: "in_progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-app:
    needs: create-check-run
    uses: ./.github/workflows/build.yml
    with:
      build_type: qa
      ref: refs/pull/${{ github.event.issue.number }}/merge
      bucket_name: ${{ inputs.bucket_name }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      KEY_STORE_FILE: ${{ secrets.KEY_STORE_FILE }}
      SIGNING_NAME: ${{ secrets.SIGNING_NAME }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  move_s3_qa:
    needs: [ create-check-run, build-app ]
    uses: ./.github/workflows/move_s3_qa.yml
    with:
      app_name: ${{ inputs.app_name }}
      bucket_name: ${{ inputs.bucket_name }}
      branch_name: ${{ needs.create-check-run.outputs.branch_name }}
      ref: refs/pull/${{ github.event.issue.number }}/merge
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  output_path_comment:
    needs: move_s3_qa
    uses: ./.github/workflows/output_path_comment.yml
    with:
      build_type: qa
      user_name: ${{ github.event.comment.user.login }}
      pr_number: ${{ github.event.issue.number }}
      output_url: https://${{ inputs.bucket_name }}.s3.ap-northeast-2.amazonaws.com/index.html#${{ needs.move_s3_qa.outputs.path }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  update-check-run:
    runs-on: ubuntu-latest
    needs: [ create-check-run, build-app, move_s3_qa ]
    if: always()
    steps:
      - name: Check Run 동기화
        uses: octokit/request-action@v2.1.9
        with:
          route: PATCH /repos/{repository}/check-runs/{check_run_id}
          repository: ${{ github.repository }}
          check_run_id: ${{ needs.create-check-run.outputs.check_run_id }}
          conclusion: ${{ needs.build-app.result }}
          status: "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

