name: Release 빌드
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.issue.number || github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
      bucket_name:
        required: false
        type: string
      extra_task:
        required: false
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
      KEY_STORE_FILE:
        required: true
      SIGNING_NAME:
        required: true
      SIGNING_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
jobs:
  check-skip:
    uses: ./.github/workflows/check_skip.yml
  build-release:
    runs-on: ubuntu-latest-8core
    needs: check-skip
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # 모든 프로젝트에서 동일한 key를 갖도록 gradle-wrapper.jar 파일을 해싱하여 사용
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.jar') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode KeyStore File
        id: decode_key_store_file
        env:
          KEY_STORE_FILE: ${{ secrets.KEY_STORE_FILE }}
        run: |
          KEY_STORE_FILE_PATH=$(echo $RUNNER_TEMP/keystore)
          echo "key_store_file_path=$KEY_STORE_FILE_PATH" >> "$GITHUB_OUTPUT"

          echo $KEY_STORE_FILE | base64 --decode > $KEY_STORE_FILE_PATH
      - name: Build with Gradle
        # 현재 위치: runner/_work/repo_name/repo_name
        # gradle user home 위치: runner/.gradle
        run: |
          GRADLE_OPTS="-Xmx16g" ./gradlew clean app:assembleQa :app:assembleQb checkQaUnitTest
          GRADLE_OPTS="-Xmx16g" ./gradlew :app:assembleRelease :app:bundleRelease checkReleaseUnitTest
        env:
          HEY_DEALER_SIGNING_PATH: ${{ steps.decode_key_store_file.outputs.key_store_file_path }}
          HEY_DEALER_SIGNING_NAME: ${{ secrets.SIGNING_NAME }}
          HEY_DEALER_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          HEY_DEALER_FOR_DEALER_SIGNING_PATH: ${{ steps.decode_key_store_file.outputs.key_store_file_path }}
          HEY_DEALER_FOR_DEALER_SIGNING_NAME: ${{ secrets.SIGNING_NAME }}
          HEY_DEALER_FOR_DEALER_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          BRANCH_NAME: ${{ github.ref }}
      - name: Extra gradle task
        if: inputs.extra_task != ''
        run: |
          ./gradlew ${{ inputs.extra_task }} --gradle-user-home "../../../.gradle"
        env:
          HEY_DEALER_SIGNING_PATH: ${{ steps.decode_key_store_file.outputs.key_store_file_path }}
          HEY_DEALER_SIGNING_NAME: ${{ secrets.SIGNING_NAME }}
          HEY_DEALER_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          HEY_DEALER_FOR_DEALER_SIGNING_PATH: ${{ steps.decode_key_store_file.outputs.key_store_file_path }}
          HEY_DEALER_FOR_DEALER_SIGNING_NAME: ${{ secrets.SIGNING_NAME }}
          HEY_DEALER_FOR_DEALER_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          BRANCH_NAME: ${{ github.ref }}
      - name: Copy to files directory
        run: |
          mkdir -p app/build/files
          find app/build/outputs/ -type f \( -name "*.apk" -o -name "*.aab" \) -exec cp {} app/build/files/ \;
      - name: Upload Files (temp directory)
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ inputs.bucket_name }}
          source_dir: "app/build/files"
          destination_dir: "tmp/${{ github.repository }}/${{ inputs.ref }}"
