name: Debug 빌드
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.issue.number || github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
jobs:
  check-skip:
    runs-on: Android
    if: |
      github.event.pull_request.draft == false
      && !contains(github.event.pull_request.title, 'skip-ci')
      && !startsWith(github.head_ref, 'feature-base')
    steps:
      - name: check-skip
        run: echo "" # no-op
  build:
    runs-on: Android # self-hosted runner
    needs: check-skip
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build with Gradle
        # 현재 위치: runner/_work/repo_name/repo_name
        # gradle user home 위치: runner/.gradle
        run: ./gradlew assembleDebug checkDebugUnitTest  --gradle-user-home "../../../.gradle"
        env:
          BRANCH_NAME: ${{ github.ref }}
