name: 앱 빌드
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
jobs:
  check-skip:
    uses: ./.github/workflows/check_skip.yml
  build-app:
    runs-on: Android # self-hosted runner
    needs: check-skip
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Decode KeyStore File
        id: decode_key_store_file
        env: 
          KEY_STORE_FILE: ${{ secrets.KEY_STORE_FILE }}
        run: |
          KEY_STORE_FILE_PATH=$(echo $RUNNER_TEMP/keystore)
          echo "key_store_file_path=$KEY_STORE_FILE_PATH" >> "$GITHUB_OUTPUT"

          echo $KEY_STORE_FILE | base64 --decode > $KEY_STORE_FILE_PATH
      - name: Build with Gradle
        # 현재 위치: runner/_work/repo_name/repo_name
        # gradle user home 위치: runner/.gradle
        run: >
          ./gradlew buildApp
          --gradle-user-home "../../../.gradle"
          -P targetBranch="${{ github.base_ref }}"
          -P commentBody="${{ github.event.comment.body }}"
        env:
          HEY_DEALER_SIGNING_PATH: ${{ steps.decode_key_store_file.outputs.key_store_file_path }}
          HEY_DEALER_SIGNING_NAME: ${{ secrets.SIGNING_NAME }}
          HEY_DEALER_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          HEY_DEALER_FOR_DEALER_SIGNING_PATH: ${{ steps.decode_key_store_file.outputs.key_store_file_path }}
          HEY_DEALER_FOR_DEALER_SIGNING_NAME: ${{ secrets.SIGNING_NAME }}
          HEY_DEALER_FOR_DEALER_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
