name: release 앱 빌드
on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
jobs:
  build-release-app:
    runs-on: migration # self-hosted runner
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build release apk
        run: ./gradlew assembleRelease 
      - name: Build release aab
        run: ./gradlew bundleRelease
      - name: Build qa apk
        run: ./gradlew assembleQa
