name: Check skip ci
on:
  workflow_call:
jobs:
  check-skip:
    runs-on: Android
    if: |
      github.event.pull_request.draft == false 
      && !contains(github.event.pull_request.title, 'skip-ci')
    steps:
      - run: echo "${{ github.event.pull_request.title }}"
