name: Release PR 생성
on:
  workflow_call:
    inputs:
      jira_version_prefix:
        required: true
        type: string
      main_branch_name:
        type: string
        default: "main"
    secrets:
      JIRA_AUTH_TOKEN:
        required: true
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Branch 추출
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF})"
      - name: Branch 출력
        run: echo "${{ steps.extract_branch.outputs.branch }}"
      - name: 버전 정보 추출
        run: echo "::set-output name=version::$(echo ${GITHUB_REF##*/} | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version
      - name: Jira 릴리즈 노트 추출
        id: release_notes
        uses: PRNDcompany/jira-release-notes@0.7
        with:
          domain: prndcompany
          project: HDA
          version: ${{ inputs.jira_version_prefix }} ${{ steps.extract_version.outputs.version }}
          auth-token: ${{ secrets.JIRA_AUTH_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: [configure]
    steps:
      - name: Release PR 생성 (main)
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ inputs.main_branch_name }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          title: "Release ${{ steps.extract_version.outputs.version }}"
          body: "# ${{ steps.release_notes.outputs.release_notes_url }}\n\n\n${{ steps.release_notes.outputs.release_notes }}"
          committer: "${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>"
          author: "${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>"
          assignees: ${{ github.event.head_commit.author.name }}
  develop:
    runs-on: ubuntu-latest
    needs: [configure, release]    
    steps:    
      - name: Release PR 생성 (develop)
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "develop"
          branch: ${{ steps.extract_branch.outputs.branch }}
          title: "Release ${{ steps.extract_version.outputs.version }} -> develop"
          body: "${{steps.create_pr.outputs.pr_url}}"
          committer: "${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>"
          author: "${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>"
          assignees: ${{ github.event.head_commit.author.name }}       