name: Release PR 생성
on:
  workflow_call:
    inputs:
      jira_version_prefix:
        required: true
        type: string
      main_branch_name:
        type: string
        default: "main"
    secrets:
      jira_auth_token:
        required: true
      github_auth_token: # github_token 예약어와의 충돌 회피
        required: true
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 버전 정보 추출
        run: echo "::set-output name=version::$(echo ${GITHUB_REF##*/} | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version
      - name: Jira 릴리즈 노트 추출
        id: release_notes
        uses: PRNDcompany/jira-release-notes@0.7
        with:
          domain: prndcompany
          project: HDA
          version: ${{ inputs.jira_version_prefix }} ${{ steps.extract_version.outputs.version }}
          auth-token: ${{ secrets.jira_auth_token }}
      - name: Release PR 생성 (main)
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ inputs.main_branch_name }}
          github_token: ${{ secrets.github_token }}
          pr_assignee: ${{ github.event.head_commit.author.name }}
          pr_title: "Release ${{ steps.extract_version.outputs.version }}"
          pr_body: "# ${{ steps.release_notes.outputs.release_notes_url }}\n\n\n${{ steps.release_notes.outputs.release_notes }}"
      - name: Release PR 생성 (develop)
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.github_token }}
          pr_assignee: ${{ github.event.head_commit.author.name }}
          pr_title: "Release ${{ steps.extract_version.outputs.version }} -> develop"
          pr_body: "${{steps.create_pr.outputs.pr_url}}"
