name: Unit Test
on:
  workflow_call:
    secrets:
      personal_access_token:
        required: true
jobs:
  unit-test:
    runs-on: Android # self-hosted runner
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.personal_access_token }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build with Gradle
        run: ./gradlew clean checkDebugUnitTest
