name: Unit Test
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
jobs:
  check-skip:
    uses: ./.github/workflows/check_skip.yml
  unit-test:
    env:
      GRADLE_USER_HOME: ../../../.gradle
    runs-on: Android # self-hosted runner
    needs: check-skip
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Build with Gradle
        run: ./gradlew checkDebugUnitTest
